In [48]:
import pandas as pd
import numpy as np
import yfinance as yf
import sys
import requests
import urllib

In [36]:
# Use the following site to get list of all publicly traded Stocks
#http://nxcoreapi.com/symbols.php

#nyse
nyse = pd.read_html('http://nxcoreapi.com/symbols.php?search=&m_exchange=NYSE&m_type=&s_type=exact&m_symbol=on&m_name=on')
#nasdaq
nqnm = pd.read_html('http://nxcoreapi.com/symbols.php?search=&m_exchange=NQNM&m_type=&s_type=exact&m_symbol=on&m_name=on')
#amex
amex = pd.read_html('http://nxcoreapi.com/symbols.php?search=&m_exchange=AMEX&m_type=&s_type=exact&m_symbol=on&m_name=on')

In [37]:
nyse = nyse[0]
nyse.columns = nyse.iloc[0]
nyse = nyse[1:]
# nyse

In [38]:
nqnm = nqnm[0]
nqnm.columns = nqnm.iloc[0]
nqnm = nqnm[1:]
# nqnm

In [39]:
amex = amex[0]
amex.columns = amex.iloc[0]
amex = amex[1:]
# amex

In [40]:
stocks = nyse
stocks = stocks.append(nqnm)
stocks = stocks.append(amex)
# stocks.tail()
# stocks

In [41]:
stocks = stocks[['Symbol', 'Name', 'Exchange']]
stocks.reset_index(inplace=True)
stocks = stocks.drop(columns=['index'])
stocks

0        Symbol                                               Name Exchange
0             A                          Agilent Technologies, Inc     NYSE
1            AA                                         Alcoa Corp     NYSE
2           AAN                                       Aaron's, Inc     NYSE
3           AAP                        Advance Auto Parts, Inc W/I     NYSE
4           AAT                         American Assets Trust, Inc     NYSE
...         ...                                                ...      ...
6276       YCBD                                        cbdMD, Inc.     AMEX
6277  YCBD.PR.A  cbdMD, Inc. 8.0% Series A Cumulative Convertib...     AMEX
6278       YUMA                                   Yuma Energy, Inc     AMEX
6279       ZDGE                                         Zedge, Inc     AMEX
6280        ZOM                      Zomedica Pharmaceuticals Corp     AMEX

[6281 rows x 3 columns]

In [42]:
symbol = yf.Ticker('AAP')
symbol.info['dividendRate']

1

In [43]:
# uncomment the following when debugging
stocks = stocks[0:20]
stocks

0     Symbol                                Name Exchange
0          A           Agilent Technologies, Inc     NYSE
1         AA                          Alcoa Corp     NYSE
2        AAN                        Aaron's, Inc     NYSE
3        AAP         Advance Auto Parts, Inc W/I     NYSE
4        AAT          American Assets Trust, Inc     NYSE
5         AB  AllianceBernstein Holding LP Units     NYSE
6        ABB                             ABB Ltd     NYSE
7       ABBV                         AbbVie, Inc     NYSE
8        ABC              AmerisourceBergen Corp     NYSE
9       ABEV                        Ambev SA ADS     NYSE
10       ABG        Asbury Automotive Group, Inc     NYSE
11       ABM                 ABM Industries, Inc     NYSE
12       ABR                  Arbor Realty Trust     NYSE
13  ABR.PR.A        Arbor Realty Trust, Inc PR A     NYSE
14  ABR.PR.B        Arbor Realty Trust, Inc PR B     NYSE
15  ABR.PR.C        Arbor Realty Trust, Inc PR C     NYSE
16       ABT                 Abbott Laboratories     NYSE
17        AC       Associated Capital Group, Inc     NYSE
18       ACA                         Arcosa, Inc     NYSE
19       ACB                Aurora Cannabis, Inc     NYSE

In [46]:
def getInfo(symbol):
    
    connection_tries=0
    j=0
    
    while 1:
        
        try:
            info = symbol.info
            return info
            
        except (urllib.error.HTTPError, requests.exceptions.ConnectionError) as e:
            if connection_tries < 2:
                print ("HTTP Error. Will try again in 30 seconds")
                time.sleep(30)
                connection_tries +=1
            elif connection_tries < 4:
                print ("HTTP Error. Will try again in 5 minutes")
                time.sleep(300)
                connection_tries +=1
            elif connection_tries < 5:
                print ("HTTP Error.  Will try again in 1 hour")
                time.sleep(3600)
                connection_tries +=1
            else:
                connection_tries = 0
                print ("HTTP Error.  Giving up.")
                break
        except:
            e = sys.exc_info()[0]
            print(e)
            if j>2:
                return {}
            j+=1

In [ ]:
i = 0
for row in stocks.itertuples():
    print (i)
    symbol = row[1]
    symbol = yf.Ticker(symbol)
    
    features = ['industry', 'sector', 'dividendRate', 'exDividendDate']
       
    info = getInfo(symbol)
    
    for feature in features:
        
        #try twice in case there's a fail that shouldn't happen
        j = 0
        while j<2:
            try:
                value = info[feature]
                stocks.at[i, feature] = value
                break
                
            except:
                print (feature)
                stocks.at[i, feature] = np.nan
                e = sys.exc_info()[0]
                print(e)
                j+=1
    
#     try:
#         stocks.loc[i, 'industry'] = symbol.info['industry']
#     except:
#         stocks.loc[i, 'industry'] = 'NA'
#         e = sys.exc_info()[0]
#         print(e)
   
#     try:
#         stocks.loc[i, 'sector'] = symbol.info['sector']
#     except:
#         stocks.loc[i, 'sector'] = 'NA'
#         e = sys.exc_info()[0]
#         print(e)

#     try:
#         stocks.loc[i, 'dividend_rate'] = symbol.info['dividendRate']
#     except:
#         stocks.loc[i, 'dividend_rate'] = 'NA'
#         e = sys.exc_info()[0]
#         print(e)

#     try:
#         stocks.loc[i, 'dividend_date'] = symbol.info['exDividendDate']
#     except:
#         stocks.loc[i, 'dividend_date'] = 'NA'
#         e = sys.exc_info()[0]
#         print(e)

    i += 1

0
1

In [18]:
stocks.to_csv('info.csv')